default_preset = "high"
device = "OV2640"
branding = "FBS3"

data_pins = "CAM_DATA"
pixel_clock_pin = "CAM_PCLK"
vsync_pin = "CAM_VSYNC"
href_pin = "CAM_HREF"
i2c = "I2C"
external_clock_pin = "CAM_XCLK"
external_clock_frequency = 20000000
powerdown_pin = "none"
reset_pin = "none"
